services:
  transactor:
    image: dev-transactor
    build: ./docker/dev-transactor
  
  peer-server:
    image: dev-peer-server
    build: ./docker/dev-peer-server
    ports:
      - "4336:4336"
    depends_on:
      - transactor
