services:
  transactor:
    image: dev-transactor
    build: ./docker/dev-transactor
    environment:
      DATOMIC_ALT_HOST: transactor
      DATOMIC_ADMIN_PASSWORD: admin
      DATOMIC_USER_PASSWORD: datomic
    expose:
      - "4334"
      - "4335"
    ports:
      - "4334:4334"
      - "4335:4335"
    volumes:
      - dbdata:/datomic-pro-1.0.6726/data
    networks:
      - backend
  
  app:
    image: clj-bball-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      DATOMIC_DB_URI: "datomic:dev://transactor:4334/db?password=datomic"
      APP_SERVER_PORT: "4337"
    ports:
      - "4337:4337"
    depends_on:
      - transactor
    networks:
      - backend
      - frontend
  
  peer-server:
    image: dev-peer-server
    build: ./docker/peer-server
    environment:
      DATOMIC_DB_URI: datomic:dev://transactor:4334/db?password=datomic
    ports:
      - "4336:4336"
    depends_on:
      - transactor
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    attachable: true
  frontend:
    attachable: true